// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SophosSyncDesktop.DataBase.Db;

#nullable disable

namespace SophosSyncDesktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SophosSyncDesktop.Models.ImpressorasConfigs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ImpressoraAux")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_aux");

                    b.Property<string>("ImpressoraBar")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_Bar");

                    b.Property<string>("ImpressoraCaixa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_caixa");

                    b.Property<string>("ImpressoraCz1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_Cz1");

                    b.Property<string>("ImpressoraCz2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_Cz2");

                    b.Property<string>("ImpressoraCz3")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("impressora_Cz3");

                    b.HasKey("Id");

                    b.ToTable("impressoras");
                });
#pragma warning restore 612, 618
        }
    }
}
